version: '3.8'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - '80:80'
    environment:
      #envsubst is used to replace the environment variables in the nginx configuration file
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: '.conf' #envsubst template suffix
      NGINX_PROTOCOL: ${PROTOCOL} #http or https
      NGINX_HOST: ${HOST} #localhost or domain name
      NGINX_API_HOST: ${API_HOST} #api.localhost or domain name
      NGINX_HOST_PORT: 80 #port number for the host
      NGINX_API_HOST_PORT: 80 #port number for the api host
    depends_on:
      - php
      - node
    networks:
      - default

  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    working_dir: /var/www
    networks:
      - default

  node:
    container_name: node
    image: node:21-alpine
    volumes:
      - ./frontend:/var/www/html
    working_dir: /var/www/html
    command: 'npm run dev'
    depends_on:
      - php
    networks:
      - default

  db:
    container_name: db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME}_db
      MYSQL_USER: ${PROJECT_NAME}_user
      MYSQL_PASSWORD: ${PROJECT_NAME}_pass
    ports:
      - '3306:3306'
    networks:
      - default

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - '8080:8080'
    volumes:
      - ./docker/adminer/adminer.css:/var/www/html/adminer.css
    depends_on:
      - db

networks:
  default:
    driver: bridge
